# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  secret_key: ultrasecretkey
  limiter: false
  image_proxy: true
ui:
  static_use_hash: true
redis:
  url: !ENV ${REDIS_URL}
